### ISSUE TITLE
vue.common.js Unexpected token

### ISSUE THREAD

**Issue by hipkiss91** [znck/rollup-plugin-vue#13]
`Error parsing C:\wamp\www\ECS\node_modules\vue\dist\vue.common.js: Unexpected token (947:29) in C:\wamp\www\ECS\node_modules\vue\dist\vue.common.js`

Is an issue I'm seeing when using vue and rollup.
I'm using vue 1.0.26.

**Comment by znck** [comment]
rollup version (?)

**Comment by hipkiss91** [comment]
Apologies its 0.34.10

**Comment by znck** [comment]
Cannot reproduce with `vue@0.34.10`, `rollup@1.0.26` and `rollup-plugin-vue@master`.

Though I have published latest source with `2.1.0-beta.1` version tag. Try compiling with this. 

Hoping this fixes your issue!

**Comment by hipkiss91** [comment]
Thanks, I'll look into it. I am using some vuex in there too - could that be the issue?

**Comment by hipkiss91** [comment]
Unfortunately this didn't solve the issue. I will assume it's something else. Thanks for checking though!

**Comment by thgh** [comment]
@hipkiss91 It's probably related to this line: https://github.com/vuejs/vue/blob/dev/dist/vue.common.js#L944

`process.env.NODE_ENV` is not set in the browser, this is resolved by rollup-plugin-vue using this hacky replace: https://github.com/znck/rollup-plugin-vue/blob/master/src/index.js#L16

**Comment by hipkiss91** [comment]
Interesting. I'll try that when I'm back in the office :)
